Repository algosup/2023-2024-project-5-flutter-team-6, pull requests merged in 2024-06, with the labels that each got.

#32 adding the user authentication
  src/adopte_un_candidat/lib/login.dart
  src/adopte_un_candidat/lib/modules/authentication.dart
  src/adopte_un_candidat/lib/routes.dart
Labels: enhancement, Code

#33 Pre-Merge to rework and avoid conflict in the future
  .vscode/settings.json
  src/adopte_un_candidat/assets/images/adopte-logo-cropped.png
  src/adopte_un_candidat/fonts/Quicksand-Medium.ttf
  src/adopte_un_candidat/fonts/Roboto-Regular.ttf
  src/adopte_un_candidat/lib/Company_cards.dart
  src/adopte_un_candidat/lib/login.dart
  src/adopte_un_candidat/lib/main.dart
  src/adopte_un_candidat/lib/modules/authentication.dart
  src/adopte_un_candidat/lib/modules/buttons.dart
  src/adopte_un_candidat/lib/modules/cards.dart
  src/adopte_un_candidat/lib/modules/database.dart
  src/adopte_un_candidat/lib/register.dart
  src/adopte_un_candidat/lib/routes.dart
  src/adopte_un_candidat/lib/swiper_feature.dart
  src/adopte_un_candidat/pubspec.yaml
  src/adopte_un_candidat/test/widget_test.dart
Labels: enhancement, Code

#38 Adding static chat screen
  src/adopte_un_candidat/lib/chat.dart
  src/adopte_un_candidat/lib/messages.dart
  src/adopte_un_candidat/lib/modules/authentication.dart
  src/adopte_un_candidat/lib/modules/database.dart
  src/adopte_un_candidat/lib/routes.dart
  src/adopte_un_candidat/lib/widgets/navigation_bar.dart
  src/adopte_un_candidat/macos/Flutter/GeneratedPluginRegistrant.swift
  src/adopte_un_candidat/pubspec.lock
  src/adopte_un_candidat/pubspec.yaml
Labels: enhancement, Code

#40 adding the authentication with the showed fields
  src/adopte_un_candidat/lib/login.dart
  src/adopte_un_candidat/lib/modules/authentication.dart
  src/adopte_un_candidat/lib/routes.dart
Labels: enhancement, Code

#41 Pushing documents to main
  .gitignore
  documents/.vscode/settings.json
  documents/functional/functional_specifications.md
  documents/images/technical/flow_chart_candidate_chat.png
  documents/images/technical/flow_chart_candidate_home_page.png
  documents/images/technical/flow_chart_candidate_home_page_2.png
  documents/images/technical/flow_chart_company_chat.png
  documents/images/technical/flow_chart_company_home_page.png
  documents/images/technical/flow_chart_company_home_page_2.png
  documents/images/technical/flow_chart_connexion.png
  documents/images/technical/flow_chart_registration_1.png
  documents/images/technical/flow_chart_registration_2.png
  documents/images/technical/quicksand_fonts.png
  documents/management/management_artifact.md
  documents/management/weekly_reports/cumulative.md
  documents/management/weekly_reports/week_1.md
  documents/management/weekly_reports/week_2.md
  documents/management/weekly_reports/week_3.md
  documents/management/weekly_reports/week_4.md
  documents/management/weekly_reports/week_5.md
  documents/management/weekly_reports/week_6.md
  documents/quality/test_plan.md
  documents/quality/to_replace.md
  documents/technical/technical_specifications.md
Labels: documentation, enhancement

#45 Profile dynamic
  src/adopte_un_candidat/lib/modules/database.dart
  src/adopte_un_candidat/lib/profile.dart
  src/adopte_un_candidat/lib/swiper_feature.dart
  src/adopte_un_candidat/lib/widgets/alert_dialogue.dart
  src/adopte_un_candidat/lib/widgets/profile_row.dart
Labels: enhancement, Code

#46 Fixing card display
  src/adopte_un_candidat/lib/modules/authentication.dart
  src/adopte_un_candidat/lib/modules/database.dart
Labels: enhancement, bug fix, Code

#52 fixing cards display
  src/adopte_un_candidat/assets/images/Algosup_logo.png
  src/adopte_un_candidat/assets/images/adopte-logo.svg
  src/adopte_un_candidat/lib/main.dart
  src/adopte_un_candidat/lib/modules/cards.dart
  src/adopte_un_candidat/lib/modules/database.dart
  src/adopte_un_candidat/lib/profile.dart
  src/adopte_un_candidat/lib/routes.dart
  src/adopte_un_candidat/lib/swiper_feature.dart
  src/adopte_un_candidat/lib/widgets/navigation_bar.dart
  src/adopte_un_candidat/lib/widgets/profile_row.dart
Labels: enhancement, bug fix, Code

#53 login validation fixed
  src/adopte_un_candidat/lib/login.dart
Labels: bug fix, Code

#54 adding tags + adding auto refill of card stack if it's empty
  src/adopte_un_candidat/lib/modules/cards.dart
  src/adopte_un_candidat/lib/swiper_feature.dart
Labels: enhancement, Code

#55 Merging the fix of the databases data collection + not complete conversations data
  src/adopte_un_candidat/lib/messages.dart
  src/adopte_un_candidat/lib/modules/cards.dart
  src/adopte_un_candidat/lib/modules/database.dart
  src/adopte_un_candidat/lib/profile.dart
Labels: enhancement, bug fix, Code

#56 adding dynamics conversation label
  src/adopte_un_candidat/lib/messages.dart
  src/adopte_un_candidat/pubspec.lock
  src/adopte_un_candidat/pubspec.yaml
Labels: enhancement, Code

#57 Adding Home buttons
  src/adopte_un_candidat/lib/home.dart
  src/adopte_un_candidat/lib/modules/database.dart
  src/adopte_un_candidat/lib/routes.dart
  src/adopte_un_candidat/lib/swiper_feature.dart
Labels: enhancement, Code

#58 adding a email update from firebase authentication system
  src/adopte_un_candidat/lib/modules/database.dart
  src/adopte_un_candidat/lib/widgets/alert_dialogue.dart
Labels: enhancement, Code

#59 adding dynamic chat (send message is still not working yet)
  src/adopte_un_candidat/lib/chat.dart
  src/adopte_un_candidat/lib/messages.dart
  src/adopte_un_candidat/lib/modules/database.dart
  src/adopte_un_candidat/lib/routes.dart
Labels: enhancement, Code

#60 fixing minor bug where a user can send message to himself
  src/adopte_un_candidat/lib/chat.dart
  src/adopte_un_candidat/lib/messages.dart
  src/adopte_un_candidat/lib/modules/database.dart
Labels: enhancement, bug fix, Code

#61 Add chat auto refresh + scrolling feature
  src/adopte_un_candidat/lib/chat.dart
Labels: enhancement, Code

#62 Chat dynamic
  src/adopte_un_candidat/lib/chat.dart
  src/adopte_un_candidat/lib/messages.dart
  src/adopte_un_candidat/lib/profile.dart
Labels: enhancement, bug fix, Code

#63 adding like logic for company
  src/adopte_un_candidat/lib/modules/database.dart
  src/adopte_un_candidat/lib/swiper_feature.dart
Labels: enhancement, Code

#66 Match system
  src/adopte_un_candidat/lib/modules/database.dart
Labels: enhancement, Code

#67 Dynamic register
  src/adopte_un_candidat/lib/modules/database.dart
  src/adopte_un_candidat/lib/register.dart
Labels: enhancement, Code

#68 Profile page not finish but need to be pushed
  src/adopte_un_candidat/lib/profile.dart
  src/adopte_un_candidat/lib/softskills.dart
  src/adopte_un_candidat/lib/widgets/carousel.dart
  src/adopte_un_candidat/lib/widgets/profile_row.dart
  src/adopte_un_candidat/lib/widgets/soft_skills_button.dart
  src/adopte_un_candidat/lib/widgets/user_soft_selection.dart
  src/adopte_un_candidat/pubspec.lock
  src/adopte_un_candidat/pubspec.yaml
Labels: enhancement, Code

#71 User manual french and english
  documents/userManual/Adopte 1 Candidat Notice d'utilisation.pdf
  documents/userManual/Adopte 1 Candidat User Manual.pdf
Labels: documentation

#74 Create README
  README.md
Labels: documentation

#75 Visual refresh register user
  src/adopte_un_candidat/lib/modules/database.dart
  src/adopte_un_candidat/lib/register.dart
Labels: bug fix, Code

#76 fixing match system
  src/adopte_un_candidat/lib/modules/database.dart
Labels: bug fix, Code

#77 Lock screen rotation
  README.md
  documents/images/management/Work breakdown structure.png
  documents/management/management_artifact.md
  documents/management/project_charter.md
  documents/management/weekly_reports/week_1.md
  documents/management/weekly_reports/week_2.md
  documents/management/weekly_reports/week_3.md
  documents/management/weekly_reports/week_4.md
  documents/management/weekly_reports/week_5.md
  documents/userManual/Adopte 1 Candidat Notice d'utilisation.pdf
  documents/userManual/Adopte 1 Candidat User Manual.pdf
  src/adopte_un_candidat/lib/favorites.dart
  src/adopte_un_candidat/lib/liste_secteur_activites.dart
  src/adopte_un_candidat/lib/main.dart
  src/adopte_un_candidat/lib/modules/database.dart
  src/adopte_un_candidat/lib/register.dart
  src/adopte_un_candidat/lib/softskills.dart
  src/adopte_un_candidat/lib/widgets/carousel.dart
  src/adopte_un_candidat/lib/widgets/user_soft_selection.dart
Labels: enhancement, bug fix, Code

#78 Fixing bug and adding features
  src/adopte_un_candidat/ios/Podfile
  src/adopte_un_candidat/ios/Podfile.lock
  src/adopte_un_candidat/ios/Runner.xcodeproj/project.pbxproj
  src/adopte_un_candidat/ios/Runner.xcworkspace/contents.xcworkspacedata
  src/adopte_un_candidat/lib/favorites.dart
  src/adopte_un_candidat/lib/liste_secteur_activites.dart
  src/adopte_un_candidat/lib/main.dart
  src/adopte_un_candidat/lib/modules/database.dart
  src/adopte_un_candidat/lib/register.dart
  src/adopte_un_candidat/lib/softskills.dart
  src/adopte_un_candidat/lib/widgets/carousel.dart
  src/adopte_un_candidat/lib/widgets/user_soft_selection.dart
Labels: enhancement, bug fix, Code

#80 Pushing the release v0.1.2 to the main
  src/adopte_un_candidat/lib/modules/cards.dart
  src/adopte_un_candidat/lib/register.dart
  src/adopte_un_candidat/lib/swiper_feature.dart
  src/adopte_un_candidat/lib/widgets/alert_dialogue.dart
  src/adopte_un_candidat/lib/widgets/navigation_bar.dart
  src/adopte_un_candidat/lib/widgets/profile_row.dart
Labels: enhancement, bug fix, Code

#81 pushing the v0.1.3
  src/adopte_un_candidat/lib/messages.dart
Labels: bug fix, Code

#83 Week6&cumulative
  documents/management/weekly_reports/cumulative.md
  documents/management/weekly_reports/week_6.md
Labels: documentation
